name: Publish Python Package

on:
  release:
    types: [created]

jobs:
  test:
    uses: ./.github/workflows/test.yml

  pypi-publish:
    runs-on: ubuntu-latest
    needs: [test]
    environment: publish
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: pip
      - name: Install poetry
        run: pipx install poetry
      - name: Install dependencies
        run: poetry install
      - name: Build package
        run: poetry build
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
