name: Publish Python Package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test:
    uses: ./.github/workflows/test.yml

  pypi-publish:
    runs-on: ubuntu-latest
    needs: [test]
    environment: publish
    permissions:
      # Required for PyPI publish via OIDC
      id-token: write

      # required to create the release
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip

      - name: Install poetry
        run: pipx install poetry

      - name: Install dependencies
        run: poetry install

      - name: Build package
        run: poetry build

      # - name: Check Version
      #   id: check-version
      #   run: |
      #     [[ "$(poetry version --short)" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || echo prerelease=true >> $GITHUB_OUTPUT

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          # prerelease: steps.check-version.outputs.prerelease == 'true'

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
